### ISSUE TITLE
Sometimes crashes when hiding mappers 

### ISSUE THREAD

**Issue by starlightnt** [Alchyr/TaikoEditor#1]
Sometimes crashes when minimizing mappers with no pattern or apparent reason. Logs:

[hs_err_pid20744.log](https://github.com/Alchyr/TaikoEditor/files/11223843/hs_err_pid20744.log)
[error.txt](https://github.com/Alchyr/TaikoEditor/files/11223844/error.txt)

**Comment by Alchyr** [comment]
this *should* be fixed in the latest version, I should really make it also put the version in the error log
