### ISSUE TITLE
add a license

### ISSUE THREAD

**Issue by chayleaf** [Alchyr/TaikoEditor#2]
Currently, your project lacks a license, which means it defaults to "all rights reserved". This means that, for example, I can't legally redistribute your source code, including modified copies, or binaries built from said source code. Additionally, I'm not sure whether you can accept contributions right now - unless the contributors grant you the license to use their code (I don't know whether "implicit agreement" works here, I'm not a lawyer), you can't legally do it.

Note that any contributions will use that license as well, so you will be bound by the terms of that license as well with regards to code contributed by others.

https://writefreesoftware.org/learn/participate/choose-a-license/

In this particular case, I'm using NixOS, and I want to package your program (and contribute code, like update Gradle and iron out any potential rough edges on Linux), but it needs to be open-source (or at least allow redistribution) to allow binary caching, without which the program will be rebuilt each time someone installs it.

**Comment by Alchyr** [comment]
you are correct
added license
